spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/learning-support
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: mkmtennislove@gmail.com
    password: bltakxcrovhrljjq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
